language: android

jdk:
  - openjdk8

android:
components:
  - tools
  - platform-tools
  - android-24
  - build-tools-24.0.2

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# script for build and release via Travis to Bintray
# script: gradle/buildViaTravis.sh

notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
